### ISSUE TITLE
Other platforms 

### ISSUE THREAD

**Issue by Sagunisaga** [kennedy69/ImgBackdoor#6]
Is it will create backdoor in Android,iPhone and more if the payload was in text format
Or give a type of payload i can use

**Comment by Sagunisaga** [comment]
Bro it's urgent please help me fast

**Comment by Sagunisaga** [comment]
Please do it fast

**Comment by Sagunisaga** [comment]
Hello anybody is there

**Comment by Tsuyoken** [comment]
> Hello anybody is there

Sorry i just making for windows only.
If u want do it by your fucking self, this project is unmaintained.
